// Multi-GPU miner PM2 config — generated by ./miner configure or ./miner start
// when MULTI_GPU=true in miner.conf. LD_LIBRARY_PATH from .env.sh (vLLM CUDA libs).
// Regenerate .env.sh with: bash scripts/setup_miner.sh
const fs = require("fs");
const path = require("path");

const REPO = __dirname;
const envSh = fs.readFileSync(path.join(REPO, ".env.sh"), "utf8");
const ldMatch = envSh.match(/^export LD_LIBRARY_PATH="([^"]*)"/m);
const LD_LIBRARY_PATH =
  process.env.LD_LIBRARY_PATH || (ldMatch && ldMatch[1]) || "";

const baseEnv = {
  LD_LIBRARY_PATH,
  VLLM_ENABLE_V1_MULTIPROCESSING: "0",
};

// GPU 0: public :40000 → backend :8000
// GPU 1: public :40001 → backend :8001
// Add more apps for additional GPUs (miner-2, miner-3, …)
module.exports = {
  apps: [
    {
      name: "miner",
      script: ".venv-vllm/bin/python",
      args: "-u -m neurons.miner --wallet <WALLET> --hotkey <HOTKEY> --netuid 96 --subtensor-network finney --model-id auto --endpoint https://YOUR_PUBLIC_IP:40000 --port 8000 --auto-update --capacity-audit-worker-poll-s 30",
      cwd: REPO,
      env: { ...baseEnv, CUDA_VISIBLE_DEVICES: "0" },
      autorestart: false,
      max_restarts: 0,
      merge_logs: true,
    },
    {
      name: "miner-1",
      script: ".venv-vllm/bin/python",
      args: "-u -m neurons.miner --wallet <WALLET> --hotkey <HOTKEY> --netuid 96 --subtensor-network finney --model-id auto --endpoint https://YOUR_PUBLIC_IP:40001 --port 8001 --auto-update",
      cwd: REPO,
      env: { ...baseEnv, CUDA_VISIBLE_DEVICES: "1" },
      autorestart: false,
      max_restarts: 0,
      merge_logs: true,
    },
  ],
};
