#!/bin/bash
# Shared helpers for Verathos miner starter scripts.
# Source this file — do not execute directly.

set -euo pipefail

# ── Colors (disabled when not a TTY) ─────────────────────────────────────────
if [ -t 1 ]; then
    _C_RESET='\033[0m'
    _C_BOLD='\033[1m'
    _C_DIM='\033[2m'
    _C_GREEN='\033[0;32m'
    _C_YELLOW='\033[1;33m'
    _C_RED='\033[0;31m'
    _C_CYAN='\033[0;36m'
    _C_BLUE='\033[0;34m'
else
    _C_RESET=''
    _C_BOLD=''
    _C_DIM=''
    _C_GREEN=''
    _C_YELLOW=''
    _C_RED=''
    _C_CYAN=''
    _C_BLUE=''
fi

miner_banner() {
    echo ""
    echo -e "${_C_BOLD}${_C_CYAN}============================================================${_C_RESET}"
    echo -e "${_C_BOLD}${_C_CYAN}  Verathos Miner Starter${_C_RESET}"
    echo -e "${_C_BOLD}${_C_CYAN}============================================================${_C_RESET}"
    echo ""
}

miner_step() {
    echo -e "${_C_BOLD}${_C_BLUE}▶ $*${_C_RESET}"
}

miner_ok() {
    echo -e "  ${_C_GREEN}✓${_C_RESET} $*"
}

miner_warn() {
    echo -e "  ${_C_YELLOW}!${_C_RESET} $*"
}

miner_fail() {
    echo -e "  ${_C_RED}✗${_C_RESET} $*"
}

miner_info() {
    echo -e "  ${_C_DIM}$*${_C_RESET}"
}

miner_die() {
    miner_fail "$*"
    echo ""
    echo "  Run:  ./miner help"
    exit 1
}

# Repo root (directory containing pyproject.toml)
miner_find_repo() {
    local dir
    dir="$(cd "$(dirname "${BASH_SOURCE[1]:-${BASH_SOURCE[0]}}")/.." && pwd)"
    if [ ! -f "$dir/pyproject.toml" ]; then
        miner_die "Cannot find Verathos repo root (expected pyproject.toml in $dir)"
    fi
    echo "$dir"
}

miner_load_config() {
    local repo="$1"
    MINER_CONF="${MINER_CONF:-$repo/miner.conf}"
    if [ ! -f "$MINER_CONF" ]; then
        miner_die "Config not found: $MINER_CONF\n  Run first:  ./miner setup"
    fi
    # shellcheck source=/dev/null
    source "$MINER_CONF"
    : "${WALLET_NAME:=miner}"
    : "${HOTKEY_NAME:=default}"
    : "${NETUID:=96}"
    : "${NETWORK:=finney}"
    : "${ENDPOINT:=}"
    : "${HTTPS_PORT:=443}"
    : "${BACKEND_PORT:=8000}"
    : "${MODEL_ID:=auto}"
    : "${PM2_NAME:=miner}"
    : "${USE_PM2:=true}"
}

miner_source_env() {
    local repo="$1"
    if [ -f "$repo/.env.sh" ]; then
        # shellcheck source=/dev/null
        source "$repo/.env.sh"
    fi
    if [ -f "$repo/.venv-vllm/bin/activate" ]; then
        # shellcheck source=/dev/null
        source "$repo/.venv-vllm/bin/activate"
    fi
}

miner_detect_public_ip() {
    curl -sf --max-time 5 ifconfig.me 2>/dev/null \
        || curl -sf --max-time 5 icanhazip.com 2>/dev/null \
        || echo ""
}

miner_check_gpu() {
    if ! command -v nvidia-smi &>/dev/null; then
        miner_fail "nvidia-smi not found — NVIDIA GPU required"
        return 1
    fi
    local name vram_mb
    name=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1)
    vram_mb=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1)
    if [ -z "$name" ]; then
        miner_fail "No GPU detected"
        return 1
    fi
    miner_ok "GPU: $name (${vram_mb} MB VRAM)"
    if [ "${vram_mb:-0}" -lt 20000 ] 2>/dev/null; then
        miner_warn "VRAM below 24 GB minimum — mining may fail"
    fi
    return 0
}

miner_check_wallet() {
    local wallet="$1" hotkey="$2"
    local hk_path="$HOME/.bittensor/wallets/${wallet}/hotkeys/${hotkey}"
    if [ ! -f "$hk_path" ]; then
        miner_fail "Wallet not found: $wallet / $hotkey"
        miner_info "Create on this machine OR copy hotkey from your laptop:"
        miner_info "  btcli wallet create --wallet.name $wallet"
        miner_info "  btcli wallet regen-hotkey --wallet.name $wallet --hotkey $hotkey"
        return 1
    fi
    miner_ok "Wallet: $wallet / $hotkey"
    return 0
}

miner_generate_ecosystem() {
    local repo="$1"
    local out="$repo/ecosystem.config.js"
    if [ -f "$out" ] && grep -qE 'name:\s*"miner-[0-9]+"' "$out" 2>/dev/null; then
        miner_warn "Keeping multi-GPU ecosystem.config.js (start with: pm2 start ecosystem.config.js)"
        return 0
    fi
    cat > "$out" <<EOF
// Auto-generated by miner-starter.sh — edit miner.conf and re-run: ./miner configure
module.exports = {
  apps: [
    {
      name: "${PM2_NAME}",
      script: ".venv-vllm/bin/python",
      args: "-u -m neurons.miner --wallet ${WALLET_NAME} --hotkey ${HOTKEY_NAME} --netuid ${NETUID} --subtensor-network ${NETWORK} --model-id ${MODEL_ID} --endpoint ${ENDPOINT} --auto-update",
      cwd: "${repo}",
      autorestart: false,
      max_restarts: 0,
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      max_size: "50M",
      retain: 3,
    },
  ],
};
EOF
    miner_ok "Wrote $out"
}

miner_prompt() {
    local var_name="$1"
    local prompt_text="$2"
    local default_val="${3:-}"
    local input
    if [ -n "$default_val" ]; then
        read -r -p "  $prompt_text [$default_val]: " input
        input="${input:-$default_val}"
    else
        read -r -p "  $prompt_text: " input
    fi
    printf -v "$var_name" '%s' "$input"
}

miner_prompt_yesno() {
    local prompt_text="$1"
    local default_yes="${2:-y}"
    local input hint="Y/n"
    [ "$default_yes" = "n" ] && hint="y/N"
    read -r -p "  $prompt_text [$hint]: " input
    input="${input:-$default_yes}"
    case "${input,,}" in
        y|yes) return 0 ;;
        *) return 1 ;;
    esac
}
